### ISSUE TITLE
怎么用呢？

### ISSUE THREAD

**Issue by GhRyuJin** [seven332/EasyRecyclerView#1]

**Comment by seven332** [comment]
你要用这个呀？我还没打算把这个弄出来给别人用。主要是 api 维护麻烦，而且懒得写文档。
我放到这里，主要是怕我的硬盘坏了。

EasyRecyclerView 主要是为 RecyclerView 添加一些 ListView 的功能。主要有
1. `void setOnItemClickListener(OnItemClickListener)`
2. `void setOnItemLongClickListener(OnItemLongClickListener)`
3. `void setSelector(Drawable)`
4. `void setChoiceMode(int)`
`setChoiceMode` 添加了个 `CHOICE_MODE_MULTIPLE_CUSTOM`。ListView 的 `CHOICE_MODE_MULTIPLE` 是自动弹出个 ActionBar，然而有些时候界面里并没有ToolBar，加上个 ActionBar 会显得很不自然。`CHOICE_MODE_MULTIPLE_CUSTOM`则是完全由开发者设计菜单形式的。EhViewer 项目里的下载界面，收藏界面，长按项目，蹦出来的 fab 就是由这个实现的。
除此之外还有 `FastScroller`，就是用手可以拖动的滑条。其他的文件没啥好说的了。

你若想看例子的话，就是我的 EhViewer 和 Nimingban，这两个项目，github 上都有。不过项目文件比较多，搜索一下，看看代码片段就行了。

如果你想把 EasyRecyclerView 放到自己的项目里，我以 Android Studio 为例。你要把 EasyRecyclerView 项目里所有的文件下载到 easyrecyclerview 的文件里，再把 easyrecyclerview 文件夹放到，项目的根目录里。再在项目根目录的 settings.gradle
里添加 `'easyrecyclerview'`，在 app/build.gradle 的 dependencies 里也要添加 `compile project(':easyrecyclerview')`。
注意 EasyRecyclerView 同时还依赖我写的别的库，你需要用同样的方式添加到自己的项目里。
如果你弄不清楚，请参照 EhViewer 和 Nimingban 项目。

**Comment by GhRyuJin** [comment]
我是在学习你EhViewer 这个项目呢，要我自己写一个能下拉刷新和上拉自动加载更多的recycleView我估计会出比较多的问题，所以想看看你这里怎么写的好借鉴一下，没想到好多！不过还是谢谢你了，通过EhViewer这个项目的学习我相信能够很大的程度上的提升自己，而且里面用到的很多新的api都是很有学习价值的，虽然现在看起来很费力。。。

**Comment by seven332** [comment]
下拉刷新那个控件不是 RecyclerView 实现的，是这个 https://github.com/seven332/EhViewer/blob/master/app/src/main/java/com/hippo/widget/refreshlayout/RefreshLayout.java 。
这个是修改自 android.support.v4.widget.SwipeRefreshLayout。
使用的话是在这里 https://github.com/seven332/EhViewer/blob/master/app/src/main/java/com/hippo/widget/ContentLayout.java

**Comment by GhRyuJin** [comment]
谢谢
